name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NUXT_TELEMETRY_DISABLED: 1

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NUXT_JWT_ACCESS_SECRET: ${{ secrets.NUXT_JWT_ACCESS_SECRET }}
          NUXT_JWT_REFRESH_SECRET: ${{ secrets.NUXT_JWT_REFRESH_SECRET }}
